"use client"
import { useState } from 'react'
import Sidebar from './components/Sidebar'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [active, setActive] = useState(false)
  function handleToggle(){
    setActive(!active)
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between bg-white relative">
        <Sidebar active={active} />
        <div className="container p-4">
        <Navbar active={active} handleToggle={handleToggle} />
        <div>{children}</div>
        </div>
        </div>
        </body>
    </html>
  )
}
